### ISSUE TITLE
Result Discrepancy in Audit Mode

### ISSUE THREAD

**Issue by noobz008** [techservicesillinois/SecOps-Powershell-CISDSC#245]
I tested a Windows 2016 server and run the 'CIS_Microsoft_Windows_Server_2016_Member_Server_Release_1607.ps1' script in  Audit mode. I was trying to validate the result manually and I've already noticed the discrepancy in the first part.

Please see screenshots of the csv file and current configuration.

![image](https://user-images.githubusercontent.com/98881833/152483666-e38733cc-ea7b-4d09-8863-fcb70e0c8eb8.png)

![image](https://user-images.githubusercontent.com/98881833/152483702-9f151067-c624-43f0-a972-e570f9648f08.png)

Those values are within the range and it should be in ResourcesInDesiredState.csv. I did not change anything in 'CIS_Microsoft_Windows_Server_2016_Member_Server_Release_1607.psd1' and 'CIS_Microsoft_Windows_Server_2016_Member_Server_Release_1607.schema.ps1'.

**Comment by edthedev** [comment]
@chokz03 Thanks for this issue report!

Can you add the full audit command you ran, including and the PowerShell version?

**Comment by MKletz** [comment]
@chokz03 there might be some confusion about what validation range is doing here. It is only protecting users from setting a value from outside the benchmark not a valid range on an audit. Since this is a configuration tool first and an audit tool second it is a bit more tedious in that regard. If you did not specify 42 as the value for your password age it will pass/fail based on it being the default of 15.

**Comment by chokz03** [comment]
@MKletz Yes, I figured it out while raising this issue. That's why I also changed the subject to be more clear with this. I got your point and understand its limitations as an audit tool. Thank you for your response.

@edthedev My question was already answered. Thank you.
